services:
  - type: web
    name: snake-online-server-pixel1igel
    runtime: docker
    rootDir: SnakeAndroid/server
    plan: free
    region: singapore
    healthCheckPath: /health
    autoDeployTrigger: commit
